rubric-dev/parte

.github/workflows/chromatic.yml
apps/storybook/package.json
packages/parte-ui/src/@foundations/Elevation/elevation.ts
packages/parte-ui/src/Alerts/Alert.styled.ts
packages/parte-ui/src/Dialog/Dialog.styled.ts
packages/parte-ui/src/DialogModal/DialogModal.tsx
packages/parte-ui/src/Dropdown/DropdownList/DropdownList.styled.ts
packages/parte-ui/src/Layout/Box.styled.ts
packages/parte-ui/src/Layout/Box.types.ts
packages/parte-ui/src/Menu/Menu.styled.ts
packages/parte-ui/src/SideSheet/SideSheet.styled.ts

:adhesive_bandage: elevation에서 border radius 속성 제거

---

.prettierrc
packages/parte-ui/src/Button/Button.styled.ts
pnpm-lock.yaml

fix #8
버튼 css 변경
- height: fit-content
- white-space: nowrap

🐛 Button 스타일 오류 수정(높이, 줄바꿈)

---

package.json

- root `package.json`에 `"packageManager": "pnpm@8.2.0"` 추가
원래 있었다가 뺐는데 git action에서 명시안해줬다고 에러나서 가장 최근 버전으로 명시해서 넣어줬습니다

:package: pnpm 버전 명시

---

packages/parte-ui/src/Button/Button.styled.ts

close #19
button height를 32px로 지정.

Parte-0463: button 보더 너비에 포함시키기

---

README.md
apps/storybook/.storybook/preview-head.html
packages/parte-ui/src/@foundations/styleReset.ts

close #14
https://github.com/styled-components/styled-components/issues/3038
참고했습니다.

:adhesive_bandage: 폰트 import를 html link나 css 파일에서 하도록 유도

---

apps/storybook/stories/Table.stories.tsx
packages/parte-ui/src/Checkbox/Checkbox.styled.ts
packages/parte-ui/src/IconButton/IconButton.styled.ts
packages/parte-ui/src/Table/Table.styled.ts
packages/parte-ui/src/Table/Table.tsx
packages/parte-ui/src/Table/Table.types.ts
packages/parte-ui/src/Table/TableTemplate.tsx

:lipstick: table border를 옵셔널하게 그리도록 처리

---

apps/web/CHANGELOG.md
apps/web/package.json
packages/parte-ui/CHANGELOG.md
packages/parte-ui/package.json

🐛 Badge의 텍스트 가운데 정렬 안되어있는 이슈 해결
🐛 Dropdown Position을 제대로 찾지 못하는 이슈
🐛 Tab을 div로 변경해서 a 태그도 넣을 수 있도록 변경

:rocket: v1.2.4

---

apps/storybook/stories/Table.stories.tsx
apps/web/src/pages/index.tsx
packages/parte-ui/src/Table/Table.styled.ts
packages/parte-ui/src/Table/Table.tsx
packages/parte-ui/src/Table/Table.types.ts
packages/parte-ui/src/Table/TableTemplate.tsx

- list table에서 그룹헤더가 지원되도록 변경했습니다

:lipstick: table group header 지원하도록 변경

---

apps/storybook/package.json
apps/web/package.json
packages/parte-ui/package.json
packages/parte-ui/src/@foundations/ThemeProvider.tsx
packages/parte-ui/src/Select/Select.tsx
packages/parte-ui/src/Select/Select.types.ts
packages/parte-ui/src/Select/index.ts
pnpm-lock.yaml

close #65 
`react-select-async-paginate`가 peer deps에 없어서 자꾸 props 타입이 any로 추론이 되었던것 ㅜ

:bug: Select 컴포넌트를 위해 peer-deps에 react-select-async-paginate 추가

---

apps/storybook/stories/Table.stories.tsx
apps/web/src/pages/index.tsx
packages/parte-ui/src/Table/Table.styled.ts
packages/parte-ui/src/Table/Table.tsx
packages/parte-ui/src/Table/Table.types.ts
packages/parte-ui/src/Table/TableTemplate.tsx

parte의 table디자인을 erp에 맞게 변경했다가 다시 되돌렸습니다!

:rewind: table style 원래대로 되돌리기

---

apps/storybook/package.json
package.json
pnpm-lock.yaml

Parte에서 사용중인 dependencies들 업데이트 하였습니다

:arrow_up: 디펜던시 업데이트

---

packages/parte-icons/src/common/Icon.tsx
packages/parte-ui/src/Alerts/Alert.styled.ts
packages/parte-ui/src/Button/Button.styled.ts
packages/parte-ui/src/Button/Button.tsx
packages/parte-ui/src/Dropdown/SelectRow/SelectRow.tsx
packages/parte-ui/src/IconButton/IconButton.tsx
packages/parte-ui/src/IconButton/IconButton.types.ts
packages/parte-ui/src/TagInput/TagInput.tsx
packages/parte-ui/src/TextInput/TextInput.tsx
packages/parte-ui/src/Textarea/Textarea.tsx

- button에 forwardRef 적용
- button vertical padding에서 1 빼기
-  button click event prevent bubbling

button 컴포넌트 수정사항

---

apps/web/src/pages/index.tsx
packages/parte-ui/src/FilePicker/FilePicker.tsx
packages/parte-ui/src/InputWrapper/InputWrapper.styled.ts
packages/parte-ui/src/InputWrapper/InputWrapper.tsx
packages/parte-ui/src/InputWrapper/InputWrapper.types.ts
packages/parte-ui/src/Select/Select.tsx
packages/parte-ui/src/Select/Select.types.ts
packages/parte-ui/src/Select/useSelectStyle.tsx
packages/parte-ui/src/TagInput/TagInput.tsx
packages/parte-ui/src/TextInput/TextInput.styled.ts
packages/parte-ui/src/TextInput/TextInput.tsx
packages/parte-ui/src/Textarea/Textarea.styled.ts
packages/parte-ui/src/Textarea/Textarea.tsx

- select내의 searchicon을 제거했습니다.
- custom width를 받을수있도록 변경했습니다
- custom style도 받을수있게 변경했습니다

:lipstick: select icon 제거 & custom width설정 & customStyle Props 추가

---

apps/web/src/pages/index.tsx
packages/parte-ui/src/FilePicker/FilePicker.styled.ts
packages/parte-ui/src/FilePicker/FilePicker.tsx
packages/parte-ui/src/InputWrapper/InputWrapper.tsx
packages/parte-ui/src/TextInput/TextInput.styled.ts
packages/parte-ui/src/TextInput/TextInput.tsx
packages/parte-ui/src/constant/DOM.ts

label이 horizontal일때의 너비 설정 방식 대응이 안되어있어서 추가해줬습니다!

:lipstick: label이 horizontal일때 너비 설정방식 변경

---

apps/web/CHANGELOG.md
apps/web/package.json
packages/parte-ui/CHANGELOG.md
packages/parte-ui/package.json

:bookmark: parte-ui v1.2.8

---

apps/web/src/@types/styled-components.d.ts
apps/web/src/pages/index.tsx
package.json
packages/parte-ui/src/InputWrapper/InputWrapper.tsx
packages/parte-ui/src/InputWrapper/InputWrapper.types.ts
packages/parte-ui/src/Select/Select.tsx
pnpm-lock.yaml

close #91 
close #92 
- InputWrapper에 `labelWidth`를 받을 수 있도록 추가
- InputWrapper에 `flex-shrink: 0` 추가
- InputWrapper에서 label이 `Horizontal`일 경우 InputWrapper 자체의 width를 상황게 맞게 조절
pnpm, turbo 버전 업

🐛 InputWrapper horizontal일때 라벨 버그 수정

---

apps/web/src/pages/_app.tsx
apps/web/src/pages/alert.tsx
apps/web/src/pages/index.tsx
apps/web/src/pages/input-wrapper.tsx
apps/web/src/pages/input.tsx
apps/web/src/pages/new-icons.tsx
packages/parte-icons/src/Icons/AlertDangerIcon.tsx
packages/parte-icons/src/Icons/AlertInfoIcon.tsx
packages/parte-icons/src/Icons/AlertSuccessIcon.tsx
packages/parte-icons/src/Icons/AlertWarningIcon.tsx
packages/parte-ui/src/Alerts/Alert.tsx

- 페이지 레이아웃 조금 수정
- Alert Icon 4종 컬러 받도록 수정
- Alert 에서 쓸때는 컬러 기존대로 유지

🩹 Alert Icon 컬러 변경 가능하도록 수정

---

apps/web/src/pages/index.tsx
packages/parte-ui/src/Checkbox/Checkbox.styled.ts
packages/parte-ui/src/Radio/Radio.styled.ts
packages/parte-ui/src/Toggle/Toggle.styled.ts

:ambulance: 체크박스, 라디오, 토글 disabled 일때 디자인 변경

---

apps/web/CHANGELOG.md
apps/web/package.json
packages/parte-ui/CHANGELOG.md
packages/parte-ui/package.json

- Checkbox, Radio, Toggle 컴포넌트 disabled일 경우 스타일링 변경
- Radio uncontrolled 지원
- TextInput padding 조건 다시 수정

:rocket: V1.3.1

---

apps/web/src/pages/index.tsx
packages/parte-ui/src/Checkbox/Checkbox.styled.ts

:bug: Checkbox 아이콘 및 아이콘 배경 색상 수정

---

apps/storybook/stories/Buttons/ButtonGroup.stories.tsx
apps/storybook/stories/Buttons/ButtonGroupOption.stories.tsx
apps/web/src/pages/index.tsx
packages/parte-ui/src/@foundations/Badge/badge.ts
packages/parte-ui/src/ButtonGroup/ButtonGroup.tsx
packages/parte-ui/src/ButtonGroup/ButtonGroup.types.ts
packages/parte-ui/src/ButtonGroup/ButtonGroupOption.tsx
packages/parte-ui/src/ButtonGroup/index.tsx
packages/parte-ui/src/index.tsx

close #111
`ButtonGroup` 컴포넌트 추가했습니다
- Badge에는 disabled이 없어서 색상을 GREY로 추가했습니다

:sparkles: ButtonGroup 컴포넌트

---

apps/storybook/stories/RangeSlider/RangeSlider.stories.tsx
packages/parte-ui/package.json
packages/parte-ui/src/RangeSlider/RangeSlider.tsx
packages/parte-ui/src/RangeSlider/RangeSlider.types.ts
packages/parte-ui/src/RangeSlider/index.ts
packages/parte-ui/src/index.tsx
pnpm-lock.yaml

close #112 
RangeSlider 추가했습니다.

:sparkles: RangeSlider 컴포넌트 추가

---

apps/storybook/stories/TextInput.stories.tsx
apps/web/src/pages/index.tsx
packages/parte-ui/src/@foundations/styleReset.ts
packages/parte-ui/src/TextInput/TextInput.styled.ts
packages/parte-ui/src/TextInput/TextInput.tsx
packages/parte-ui/src/TextInput/TextInput.types.ts

:sparkles: input type이 number일떄 spin button 보여지도록 변경

---

apps/storybook/.storybook/decorators/GlobalStyles.tsx
apps/storybook/stories/Alerts/Alert.mdx
apps/storybook/stories/Alerts/Alert.stories.tsx
apps/storybook/stories/Alerts/Toaster.stories.tsx
apps/storybook/stories/AvatarsAndBadges/Avatar.stories.tsx
apps/storybook/stories/AvatarsAndBadges/Badge.stories.tsx
apps/web/src/pages/alert.tsx
apps/web/src/pages/table.tsx
apps/web/src/pages/toast/index.tsx
packages/parte-ui/src/Alerts/Alert.styled.ts
packages/parte-ui/src/Alerts/Alert.tsx
packages/parte-ui/src/Alerts/Alert.types.ts
packages/parte-ui/src/Alerts/index.ts
packages/parte-ui/src/Toaster/Toast.tsx
packages/parte-ui/src/Toaster/ToastManager.tsx
packages/parte-ui/src/Toaster/Toaster.types.ts
packages/parte-ui/src/constants/index.ts

close #124
close #103 
- Alerts 컴포넌트의 props를 직관적으로 수정
- props가 html attributes로 들어가는것을 방지
- Docs 작성

✨ Alert 컴포넌트 수정 및 Docs 작성

---

apps/web/src/pages/alert.tsx
packages/parte-ui/src/Alerts/Alert.styled.ts
packages/parte-ui/src/Alerts/Alert.tsx
packages/parte-ui/src/Toaster/Toast.tsx
packages/parte-ui/src/Toaster/ToastManager.styled.ts
packages/parte-ui/src/Toaster/ToastManager.tsx
packages/parte-ui/src/Toaster/Toaster.types.ts

close #144
- 토스트를 감싸는 영역이 넓어서 뒤에 클릭 요소가 있을 경우 클릭이 안되는 이슈 해결

:bug: 토스트 영역이 넓어 클릭 안되는 이슈 수정

---

apps/web/src/pages/select/index.tsx
packages/parte-ui/src/Select/Select.tsx
packages/parte-ui/src/Select/Select.types.ts
packages/parte-ui/src/Select/useSelectStyle.tsx

Select 컴포넌트 react-select에 맞게 타입 추론 가능 하도록 변경

:label: React select type gymnastics

---

packages/parte-icons/src/Icons/StyleShareIcon.tsx
packages/parte-ui/src/@foundations/styleReset.ts

```
client.js:1 Warning: Invalid DOM property `stroke-linejoin`. Did you mean `strokeLinejoin`?
```
에러 해결

:adhesive_bandage: JSX Attribute 수정

---

apps/web/CHANGELOG.md
apps/web/package.json
packages/parte-ui/CHANGELOG.md
packages/parte-ui/package.json
packages/parte-ui/src/Dropdown/DropdownList/styleUtil.ts

Revert ":lipstick: 드롭다운 리스트 중앙 정렬"

---

apps/web/CHANGELOG.md
apps/web/package.json
packages/parte-ui/CHANGELOG.md
packages/parte-ui/package.json
packages/parte-ui/src/Dropdown/DropdownList/DropdownList.styled.ts
packages/parte-ui/src/Dropdown/SelectRow/SelectRow.styled.ts

Revert ":lipstick: 드롭다운 리스트 텍스트 길어지면 ellipsis"
